// Fixes a real gap flagged by an automated PR review: globals.css imports
// Tailwind, but without this file (and @tailwindcss/postcss installed),
// Tailwind's utility classes are never actually generated by the build.
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
